package com.alexisgordr.icdetector.ui

/**
 * Traducción al inglés de las líneas del terminal y de las explicaciones de diagnóstico, que el
 * servicio genera en castellano. Es solo presentación: el texto original se guarda y se exporta tal
 * cual.
 *
 * v2.10.6 — La tabla se aplica de la frase más larga a la más corta. Antes se aplicaba en el orden
 * en que estaba escrita, y una palabra suelta ("anómala") se traducía dentro de una frase larga
 * ("La condición anómala…") antes de que la frase completa pudiera reconocerse, dejando líneas a
 * medio traducir. Separada de Terminal.kt para poder probarla en la JVM.
 */
internal fun localizeTerminalLine(line: String): String {
    var translated = line
    orderedReplacements.forEach { (source, target) -> translated = translated.replace(source, target, ignoreCase = true) }
    return translated
}

private val replacements = linkedMapOf(
    // v2.10.8 — Prefijo de las observaciones sub-umbral. El dato guardado sigue en castellano
    // (SUBTHRESHOLD_PREFIX); solo se traduce al mostrarlo.
    "[sub-umbral]" to "[sub-threshold]",
    // v2.10.4 — Líneas [RADIO] y [SERVICIO]. Van antes que las genéricas ("Celda ", etc.)
    // y las frases largas antes que las cortas que contienen.
    "[SERVICIO]" to "[SERVICE]",
    "Estado de servicio" to "Service state",
    "EN SERVICIO" to "IN SERVICE",
    "SIN SERVICIO" to "OUT OF SERVICE",
    "SOLO EMERGENCIAS" to "EMERGENCY ONLY",
    "RADIO APAGADA" to "RADIO OFF",
    "red anunciada distinta de la SIM sin roaming" to "network PLMN differs from SIM without roaming",
    "selección manual de red" to "manual network selection",
    " no registrado ·" to " not registered ·",
    " registrado ·" to " registered ·",
    "roaming=sí" to "roaming=yes",
    " · datos=" to " · data=",
    " · red=" to " · network=",
    "sin portadoras secundarias" to "no secondary carriers",
    "portadoras secundarias" to "secondary carriers",
    "estado de conexión" to "connection state",
    "entradas registradas" to "registered entries",
    "Servidora " to "Serving ",
    "Celda de grupo cerrado" to "Closed subscriber group cell",
    "posible femtocelda" to "possible femtocell",
    " nombre=" to " name=",
    "Celda ya verificada" to "Cell already verified",
    "Coordenadas frescas rellenadas" to "Fresh coordinates filled",
    "GPS inestable tras espera" to "GPS unstable after waiting",
    "GPS estabilizado" to "GPS stabilized",
    "Solicitando fix GPS preciso" to "Requesting precise GPS fix",
    "Fix GPS preciso no disponible" to "Precise GPS fix unavailable",
    "Handover celular completado" to "Cellular handover completed",
    // 3.0 (#20)
    "Continuidad interrumpida por pérdida de señal: la confirmación vuelve a empezar." to
        "Continuity interrupted by signal loss: confirmation starts again.",
    "Nueva celda" to "New cell",
    "Ping-Pong observado" to "Ping-pong observed",
    "Sin credenciales configuradas" to "No credentials configured",
    "Verificando antena" to "Verifying cell",
    "Antena no identificada" to "Cell not identified",
    "Validación OK" to "Validation OK",
    "Error al verificar" to "Verification error",
    "Respuesta descartada" to "Response rejected",
    "Ubicación continua activa" to "Continuous location active",
    "Batería crítica" to "Critical battery",
    "Alimentación recuperada" to "Power recovered",
    "Modo Avión activo" to "Airplane mode active",
    "Conexión restaurada" to "Connection restored",
    "Escritura en base de datos restablecida" to "Database writes restored",
    "Movimiento detectado" to "Movement detected",
    "ICdetector Engine Iniciado" to "ICdetector engine started",
    "Esperando hooks del módem" to "Waiting for modem callbacks",
    "Error en ciclo de escaneo" to "Scanning-cycle error",
    "se continúa" to "continuing",
    "ubicación continua en pausa" to "continuous location paused",
    "recolección 24/7 reanudadas" to "24/7 collection resumed",
    "Suspendiendo escaneo" to "Pausing scanning",
    "Analizando nueva celda activa" to "Analyzing new serving cell",
    "Fix disponible pero no lo bastante fresco" to "Fix available but not fresh enough",
    "se omite el relleno" to "coordinate backfill skipped",
    "espera al fix preciso" to "waiting for a precise fix",
    "sin necesidad de API" to "API query not required",
    "relanzando verificación" to "retrying verification",
    "sin confirmar; sin tono" to "unconfirmed; no alert tone",
    "Ignorando alerta" to "Ignoring alert",
    "ESCRITURA FALLIDA" to "WRITE FAILED",
    "la base de datos rechaza las filas" to "the database is rejecting rows",
    "disco lleno" to "disk full",
    "La recolección NO está guardando datos" to "Collection is NOT saving data",
    "Coordenada rechazada" to "Coordinate rejected",
    "áreas de seguimiento sin relación entre sí" to "unrelated tracking areas",
    "valor por defecto de la API" to "API default value",
    "no identifica ninguna antena" to "does not identify a cell",
    "de tu posición de referencia" to "from your reference position",
    "índice heurístico" to "heuristic score",
    "CICLO DE AUDITORÍA" to "AUDIT CYCLE",
    "reglas evaluadas" to "rules evaluated",
    "16 REGLAS" to "16 RULES",
    "sin fallos" to "without failures",
    "Sin anomalías en las reglas que pudieron evaluarse" to "No anomalies in the rules that could be evaluated",
    "Sin alarma, pero con observaciones" to "No alarm, but observations remain",
    "Antena sospechosa detectada" to "Suspicious cell detected",
    "El módem no reporta Timing Advance en esta celda" to "The modem does not report Timing Advance for this cell",
    "no juzga geometría" to "does not assess geometry",
    "de la antena" to "from the cell",
    "sin conversión defendible" to "no defensible conversion",
    "no se usa para geometría" to "not used for geometry",
    "Ve a Ajustes para añadir OpenCellID" to "Open Settings to add OpenCellID",
    "Esta antena ya constaba verificada" to "This cell was already verified",
    "una consulta vacía o fallida no borra esa evidencia" to "an empty or failed query does not erase that evidence",
    "Se reintentará" to "Will retry",
    "no permite afirmar ni desmentir nada sobre esta antena" to "provides no evidence for or against this cell",
    "Firmas geográficas obtenidas" to "Geographic signatures obtained",
    "Poda de histórico" to "History pruning",
    "registros de más de" to "records older than",
    "días eliminados" to "days deleted",
    "Muestras forenses recortadas" to "Forensic samples trimmed",
    // v2.8.0 — Poda forense por casos completos y salud de la escritura de muestras.
    "Poda forense" to "Forensic pruning",
    "caso(s) cerrado(s) eliminados enteros" to "closed case(s) deleted in full",
    "muestras) para respetar el tope de" to "samples) to respect the cap of",
    "Restantes" to "Remaining",
    "Tope forense superado" to "Forensic cap exceeded",
    "muestras) con solo casos abiertos" to "samples) with only open cases left",
    "No se recortan: una captura en curso no se mutila." to
        "Not trimmed: a capture in progress is never mutilated.",
    "Captura forense degradada — las muestras no se están guardando." to
        "Forensic capture degraded — samples are not being saved.",
    "Captura forense restablecida." to "Forensic capture restored.",
    "Mantenimiento de base de datos fallido" to "Database maintenance failed",
    "No se pudo registrar" to "Could not register",
    "Red 2G/3G detectada" to "2G/3G network detected",
    "Abriendo ajustes para Modo Avión manual" to "Opening settings for manual Airplane mode",
    "Latencia" to "Latency",
    "sin suficientes endpoints disponibles" to "not enough endpoints available",
    "anómala" to "anomalous",
    "media" to "average",
    "ANOMALÍA DE RED PERSISTENTE" to "PERSISTENT NETWORK ANOMALY",
    "posible interferencia" to "possible interference",
    "normalizada" to "normalized",
    "aprendiendo baseline" to "learning baseline",
    "Señal sospechosamente fuerte detectada" to "Suspiciously strong signal detected",
    "Efecto Ping-Pong confirmado" to "Ping-pong effect confirmed",
    "detección de cifrado nulo/IMSI: pendiente API Android 16" to "null-cipher/IMSI detection: awaiting Android 16 API",
    "Transición coherente" to "Coherent transition",
    "Transición incoherente" to "Incoherent transition",
    "respuesta descartada por coordenada no creíble" to "response rejected due to implausible coordinates",
    "No se concluye nada sobre la antena" to "No conclusion can be drawn about the cell",
    "respuesta sin coordenadas" to "response without coordinates",
    "no se puede comprobar" to "cannot be verified",
    "Estabilidad Potencia" to "Power stability",
    "Potencia vs Histórico" to "Power vs history",
    "Downgrade de Banda" to "Band downgrade",
    "Celda Aislada" to "Isolated cell",
    "Consistencia MCC" to "MCC consistency",
    "Límite MNC" to "MNC limit",
    "Validación Regional TAC" to "Regional TAC validation",
    "Geometría (TA)" to "Geometry (TA)",
    "Cifrado Nulo" to "Null ciphering",
    "Sanidad ARFCN" to "ARFCN sanity",
    "Integridad PCI" to "PCI integrity",
    "Consistencia Geográfica" to "Geographic consistency",
    "Correlación Latency + RF" to "Latency + RF correlation",
    "Correlación Latencia + RF" to "Latency + RF correlation",
    "Reputación de Celda" to "Cell reputation",
    "Coherencia de Transición" to "Transition coherence",
    "Resultado provisional (falta la verificación)" to "Provisional result (verification pending)",
    "Resultado Global" to "Overall result",
    "Auditoría en curso" to "Audit in progress",
    "Auditoría completada" to "Audit completed",
    "registrada en bases públicas" to "registered in public databases",
    "sin registro en bases públicas" to "not registered in public databases",
    "respuesta descartada o no creíble" to "rejected or implausible response",
    "no concluye nada sobre la antena" to "provides no conclusion about the cell",
    "las bases públicas no han contestado" to "public databases did not respond",
    "verificación pendiente" to "verification pending",
    "Falta la respuesta de las bases públicas" to "Waiting for the public-database response",
    "sin datos" to "unavailable",
    "CRÍTICO" to "CRITICAL",
    "El módem devuelve 0 en todas las celdas" to "The modem returns 0 for every cell",
    "distintas comprobadas" to "distinct cells checked",
    "el campo no está poblado y H6 queda N/A" to "the field is unpopulated and H6 remains N/A",
    "a menos de un paso de TA" to "less than one TA step",
    "No es una medida de 0 m" to "This is not a 0 m measurement",
    "es el escalón mínimo" to "it is the minimum step",
    "Consumo de batería elevado por diseño" to "High battery consumption by design",
    "las coordenadas son necesarias" to "coordinates are required",
    "hasta conectar el cargador" to "until the charger is connected",
    "para fijar coordenadas" to "to capture coordinates",
    "reintentando más tarde" to "retrying later",
    "Incidente localizado" to "Incident geolocated",
    "con coordenadas precisas" to "with precise coordinates",
    "Fix preciso obtenido" to "Precise fix obtained",
    "sin registros pendientes de coordenadas" to "no records awaiting coordinates",
    "Diagnóstico de TA recuperado del arranque anterior" to "TA diagnosis restored from the previous run",
    "el módem no rellena el campo" to "the modem does not populate the field",
    "Recolección interrumpida" to "Collection interrupted",
    "sin registrar nada desde la última escritura" to "nothing recorded since the last write",
    "Revisa si el servicio se detuvo" to "Check whether the service stopped",
    "reinicio del móvil" to "phone restart",
    "batería agotada" to "empty battery",
    "no se están guardando datos" to "data is not being saved",
    "ya consta en" to "already appears in",
    "registros" to "records",
    "eliminadas" to "deleted",
    "límite diario de consultas agotado" to "daily query limit exhausted",
    "NO significa que la antena no exista" to "This does NOT mean the cell does not exist",
    "demasiadas peticiones seguidas" to "too many consecutive requests",
    "la API key no es válida o no tiene permiso" to "the API key is invalid or lacks permission",
    "Revísala en Ajustes" to "Review it in Settings",
    "servicio temporalmente no disponible" to "service temporarily unavailable",
    "esta celda no está en su base" to "this cell is not in its database",
    "respuesta sin coordenadas y sin código de error" to "response without coordinates or an error code",
    "Respuesta" to "Response",
    "Celda detectada a distancia anómala" to "Cell detected at an anomalous distance",
    "Salto potencia" to "Signal-power jump",
    "Desviación TAC" to "TAC deviation",
    "Suplantación TA" to "TA spoofing",
    "Proximidad anómala" to "Anomalous proximity",
    "Cambios rápidos en parado" to "Rapid changes while stationary",
    "Consistencia geográfica fallida" to "Geographic consistency failed",
    "RF anómalo" to "Anomalous RF",
    "posible MITM" to "possible MITM",
    "Potencia anómala vs historial" to "Anomalous power vs history",
    "Transición celular incoherente" to "Incoherent cellular transition",
    "Episodio multiseñal" to "Multi-signal episode",
    "Cambio en identidad celular consolidada" to "Established local cell identity changed",
    "familias independientes" to "independent families",
    "todavía no se ha observado un handover evaluable" to "no evaluable handover has been observed yet",
    "faltan dos posiciones GPS contemporáneas" to "two contemporaneous GPS positions are unavailable",
    "la precisión GPS es insuficiente" to "GPS accuracy is insufficient",
    "se exige" to "required",
    "Transición aprendida previamente" to "Previously learned transition",
    "observaciones coherentes" to "coherent observations",
    "baseline geográfico en aprendizaje" to "geographic baseline still learning",
    "Handover incoherente" to "Incoherent handover",
    "el móvil recorrió" to "the phone moved",
    "Desplazamiento compatible con las zonas históricas" to "Movement consistent with historical areas",
    "Datos disponibles; no se observó la condición anómala" to "Data available; the anomalous condition was not observed",
    "La condición anómala de esta regla está presente en el ciclo actual" to "This rule's anomalous condition is present in the current cycle",
    "Wi-Fi activo; se evita atribuir el contexto de red al enlace celular" to "Wi-Fi active; network context is not attributed to the cellular link",
    "sin lectura celular válida" to "no valid cellular reading",
    "hacen falta celdas vecinas con potencia para comparar" to "neighbor cells with signal readings are required for comparison",
    "falta MCC válido en la celda activa o en sus vecinas" to "the serving cell or its neighbors lack a valid MCC",
    "faltan MNC válidos de celdas vecinas" to "valid MNC values from neighbor cells are unavailable",
    "no hay TAC válidos de vecinas para contrastar" to "no valid neighbor TAC values are available for comparison",
    "el módem no entrega un Timing Advance convertible a metros" to "the modem does not provide Timing Advance convertible to meters",
    "no hay celdas vecinas disponibles para contrastar el espectro" to "no neighbor cells are available for spectrum comparison",
    "el módem no entrega ARFCN/EARFCN para esta tecnología" to "the modem does not provide ARFCN/EARFCN for this technology",
    "Android o el fabricante no exponen el estado de cifrado a esta app" to "Android or the manufacturer does not expose ciphering status to this app",
    "estado de cifrado no disponible" to "ciphering status unavailable",
    "todavía no existe una secuencia temporal utilizable" to "no usable temporal sequence exists yet",
    "falta una posición GPS reciente" to "a recent GPS position is unavailable",
    "aún no hay observaciones previas geolocalizadas de esta celda" to "this cell has no previous geolocated observations yet",
    "identidad celular insuficiente para comparar" to "insufficient cell identity for comparison",
    "Wi-Fi/VPN impide atribuir la latencia al enlace celular" to "Wi-Fi/VPN prevents attributing latency to the cellular link",
    "la sonda de latencia todavía no tiene una medición válida" to "the latency probe does not yet have a valid measurement",
    "el módem no entrega RSRQ ni SINR" to "the modem provides neither RSRQ nor SINR",
    "faltan datos cruzados del ciclo" to "cross-signal data is unavailable for this cycle",
    "baseline en aprendizaje; se necesitan muestras históricas compatibles" to "baseline still learning; compatible historical samples are required",
    "falta una banda LTE anterior válida para comparar" to "a previous valid LTE band is unavailable for comparison",
    "la tecnología o banda actual no permite la comparación" to "the current technology or band does not allow comparison",
    "historial RF insuficiente" to "insufficient RF history",
    "observaciones" to "observations",
    "Celda " to "Cell ",
    "Antena " to "Cell ",
    "sobre " to "across ",
    "más tarde" to "later",
    "fresco" to "fresh",
    // v2.10.6 — Frases que llegaban al terminal sin traducir. Van completas: al aplicarse de la más
    // larga a la más corta no las rompen las entradas cortas de arriba.
    // AuditLogController
    "sin registro en OpenCellID; no resta puntos porque esa base es incompleta" to "not in OpenCellID; no points deducted because that database is incomplete",
    "respuesta descartada o no creíble; no concluye nada sobre la antena" to "response discarded or not credible; nothing is concluded about the antenna",
    "pendiente de verificar" to "pending verification",
    "CICLO DE AUDITORÍA" to "AUDIT CYCLE",
    "7. Espectro Fantasma" to "7. Ghost Spectrum",
    "9. Cifrado Hardware" to "9. Hardware Ciphering",
    "11. Consistencia Geográfica (Cell ID móvil)" to "11. Geographic Consistency (moving Cell ID)",
    "13. Potencia vs Histórico (Baseline + huella RSRQ/SINR)" to "13. Power vs History (Baseline + RSRQ/SINR fingerprint)",
    "15. Estabilidad de Identidad RF (PCI)" to "15. RF Identity Stability (PCI)",
    "Resultado provisional (falta la verificación)" to "Provisional result (verification pending)",
    "% sobre " to "% over ",
    "Sin alarma, pero con observaciones:" to "No alarm, but with observations:",
    "Sin anomalías en las reglas que pudieron evaluarse." to "No anomalies in the rules that could be evaluated.",
    "El módem no reporta Timing Advance en esta celda (H6 no juzga geometría)." to "The modem reports no Timing Advance for this cell (H6 does not judge geometry).",
    "El módem devuelve 0 en todas las celdas (" to "The modem returns 0 for every cell (",
    " distintas comprobadas): " to " distinct cells checked): ",
    "no es una medida, es un campo sin rellenar. No se deduce distancia." to "it is not a measurement, it is an empty field. No distance is inferred.",
    "→ a menos de un paso de TA de la antena (<" to "→ less than one TA step from the antenna (<",
    "No es una medida de 0 m: es el escalón mínimo." to "It is not a 0 m measurement: it is the smallest step.",
    " m de la antena." to " m from the antenna.",
    "— sin conversión defendible; no se usa para geometría." to "— no defensible conversion; not used for geometry.",
    "Diagnóstico de TA recuperado del arranque anterior: el módem no rellena el campo " to "TA diagnosis restored from the previous start: the modem does not fill the field ",
    " celdas distintas con 0). No se deduce distancia." to " distinct cells with 0). No distance is inferred.",
    // MiniICService
    "portadoras secundarias=" to "secondary carriers=",
    "sin portadoras secundarias" to "no secondary carriers",
    "Primaria declarada sin señal utilizable: ciclo en abstención." to "Declared primary has no usable signal: cycle abstains.",
    "Ubicación continua activa (24/7). Consumo de batería elevado por diseño: las coordenadas son necesarias para H11, H13 y H16." to "Continuous location active (24/7). High battery use by design: coordinates are needed for H11, H13 and H16.",
    "Batería crítica (<" to "Critical battery (<",
    "%): ubicación continua en pausa hasta conectar el cargador." to "%): continuous location paused until the charger is connected.",
    "Alimentación recuperada: ubicación continua y recolección 24/7 reanudadas." to "Power restored: continuous location and 24/7 collection resumed.",
    "Incidente localizado: " to "Incident located: ",
    " registro(s) con coordenadas precisas" to " record(s) with precise coordinates",
    "Fix preciso obtenido (sin registros pendientes de coordenadas)" to "Precise fix obtained (no records waiting for coordinates)",
    "Protección=" to "Protection=",
    ", sitio=detectado" to ", site=detected",
    ", sitio=no disponible" to ", site=unavailable",
    "movimiento=" to "motion=",
    ", vecinos=" to ", neighbours=",
    " días, capacidad=" to " days, capability=",
    ", madurez=" to ", maturity=",
    ", aplicación=" to ", enforcement=",
    "SOMBRA: aplicaría SITE_UNVERIFIED" to "SHADOW: would apply SITE_UNVERIFIED",
    "=NO ACTIVA" to "=INACTIVE",
    "Coordenadas frescas rellenadas en " to "Fresh coordinates filled in ",
    " registro(s)" to " record(s)",
    "Celda ya verificada en DB, sin necesidad de API" to "Cell already verified in DB, no API call needed",
    "Ping-Pong observado (sin confirmar; sin tono)." to "Ping-Pong observed (unconfirmed; no tone).",
    "Ping-Pong detectado a " to "Ping-Pong detected at ",
    "Cambios rápidos de celda observados a " to "Rapid cell changes observed at ",
    "Cambios rápidos de celda observados sin velocidad GPS (H10 en N/A)." to "Rapid cell changes observed without GPS speed (H10 N/A).",
    "N/A: hay cambios rápidos de celda, pero sin velocidad GPS no se puede saber si estás parado." to "N/A: rapid cell changes, but without GPS speed it is unknown whether you are stationary.",
    "Efecto Ping-Pong confirmado por TemporalConfidence." to "Ping-Pong effect confirmed by TemporalConfidence.",
    "N/A: sin handover reciente; esperando el siguiente para comprobar la movilidad." to "N/A: no recent handover; waiting for the next one to check mobility.",
    "Tope forense superado (" to "Forensic cap exceeded (",
    " muestras) con solo casos abiertos. No se recortan: una captura en curso no se mutila." to " samples) with only open cases. Nothing is trimmed: a capture in progress is never cut short.",
    "No se pudo registrar el fix GPS preciso: " to "Could not request the precise GPS fix: ",
    "Fix GPS preciso no disponible en " to "Precise GPS fix not available in ",
    // ExternalVerificationController / VerificationDecision / clientes
    "Sin credenciales configuradas. Ve a Ajustes para añadir OpenCellID." to "No credentials configured. Go to Settings to add OpenCellID.",
    "OpenCellID: respuesta descartada por coordenada no creíble. No se concluye nada sobre la antena." to "OpenCellID: response discarded because of a non-credible coordinate. Nothing is concluded about the antenna.",
    "Antena no identificada en OpenCellID. Se reintentará en 1 h." to "Antenna not identified in OpenCellID. Retrying in 1 h.",
    "Respuesta descartada: no permite afirmar ni desmentir nada sobre esta antena." to "Response discarded: it neither confirms nor rules out anything about this antenna.",
    "HTTP 404 (endpoint no encontrado). No dice nada sobre la antena." to "HTTP 404 (endpoint not found). Says nothing about the antenna.",
    "respuesta no interpretable (HTTP " to "unreadable response (HTTP ",
    " de la API. Respuesta:" to " from the API. Response:",
    "la respuesta no es de la celda preguntada. No verifica nada, y tampoco demuestra que la antena no esté." to "the response is not for the requested cell. It verifies nothing, and does not prove the antenna is absent either.",
    "sin conexión o respuesta ilegible." to "no connection or unreadable response.",
    // DiagnosticEngine / TransitionCoherence
    "N/A: Wi-Fi activo; se evita atribuir el contexto de red al enlace celular." to "N/A: Wi-Fi active; network context is not attributed to the cellular link.",
    "N/A: sin lectura celular válida." to "N/A: no valid cellular reading.",
    "Estabilidad de potencia" to "Power stability",
    "N/A: no hay TAC válidos de vecinas para contrastar." to "N/A: no valid neighbour TACs to compare.",
    "Coherencia geométrica (TA)" to "Geometric coherence (TA)",
    "Espectro de vecinos" to "Neighbour spectrum",
    "N/A: no hay celdas vecinas disponibles para contrastar el espectro." to "N/A: no neighbour cells available to compare the spectrum.",
    "Cifrado hardware" to "Hardware ciphering",
    "N/A: todavía no existe una secuencia temporal utilizable." to "N/A: no usable time sequence yet.",
    "N/A: aún no hay observaciones previas geolocalizadas de esta celda." to "N/A: no previous geolocated observations of this cell yet.",
    "Baseline y huella RF" to "Baseline and RF fingerprint",
    "Estabilidad de identidad RF" to "RF identity stability",
    "Coherencia de transición celular" to "Cell transition coherence",
    "N/A: todavía no se ha observado un handover evaluable." to "N/A: no evaluable handover observed yet.",
    "no hubo cambio de celda." to "there was no cell change.",
    "el intervalo entre observaciones no permite atribuir el desplazamiento al handover." to "the interval between observations does not allow attributing the movement to the handover.",
    "La celda destino ya era vecina visible antes del handover." to "The destination cell was already a visible neighbour before the handover.",
    " origen, " to " origin, ",
    " destino)." to " destination).",
    "pero las zonas aprendidas quedan a " to "but the learned zones are ",
    " m y no se solapan." to " m apart and do not overlap.",
    "La celda destino se anunciaba como vecina." to "The destination cell was advertised as a neighbour.",
    " m recorridos; centros a " to " m travelled; distance between centres ",
    // ThreatAnalyzer (motivos)
    "Inconsistencia RF (PCI/ARFCN) detectada a gran distancia" to "RF inconsistency (PCI/ARFCN) detected at long range",
    "Multitud de MNCs" to "Many MNCs",
    "Vecinos fantasma" to "Ghost neighbours",
    "Frecuencia (ARFCN) 5G sospechosa" to "Suspicious 5G frequency (ARFCN)",
    "Frecuencia (EARFCN) 4G sospechosa" to "Suspicious 4G frequency (EARFCN)",
    "Cifrado de red anulado (A5/0)" to "Network ciphering disabled (A5/0)",
    "Efecto Ping-Pong (Cambios rápidos en parado)" to "Ping-Pong effect (rapid changes while stationary)",
    "Huella RF incoherente con el historial (RSRQ/SINR muy desviados)" to "RF fingerprint inconsistent with history (RSRQ/SINR far off)",
    "Downgrade de banda forzado" to "Forced band downgrade",
    "Identidad RF inestable: misma Cell ID alternando PCI en la misma portadora (posible clon)" to "Unstable RF identity: same Cell ID alternating PCI on the same carrier (possible clone)",
    // ServiceStateTracker / TemporalConfidence
    " ciclos confirmando]" to " cycles confirming]",
    "SUPERADA" to "PASSED",
    "FALLIDA" to "FAILED",
    "NO EVALUADA" to "NOT EVALUATED"
)

private val orderedReplacements: List<Pair<String, String>> =
    replacements.entries.sortedByDescending { it.key.length }.map { it.key to it.value }
